battery_capacities:
- 640.0
data_path: Data/EXPECTED_DATA/data_expected_lat30.0_lon-90.0_15min.pkl
episodes: 1000
horizon: 10000
latitude: 30.0
longitude: -90.0
solar_panel_model: constant
start_datetime: '2022-04-01T00:00:00'
threshold_values:
- 0.0
- 0.25
transition_model: moderate
wind_thresholds:
- 1.0
- 3.0
- 5.0
