battery_capacities:
- 600.0
episodes: 10
horizon: 100
locations:
- data_path: Data/EXPECTED_DATA/data_expected_lat30.0_lon-90.0_15min.pkl
  latitude: 30.0
  longitude: -90.0
- data_path: Data/EXPECTED_DATA/data_expected_lat0.0_lon-90.0_15min.pkl
  latitude: 0.0
  longitude: -90.0
solar_panel_model: constant
start_datetime: '2023-04-01T00:00:25'
threshold_values:
- 0.02
transition_model: moderate
wind_thresholds:
- 5.0
- 10.0
- 15.0
