battery_capacities:
- 300.0
data_path: Data/EXPECTED_DATA/data_expected_lat0.0_lon-90.0_15min.pkl
episodes: 300
horizon: 10
latitude: 0.0
longitude: -90.0
solar_panel_model: constant
start_datetime: '2025-04-18T00:00:50'
threshold_values:
- 0.2
transition_model: moderate
wind_thresholds:
- 5.0
