battery_capacities:
- 400.0
data_path: Data/EXPECTED_DATA/data_expected_lat0.0_lon-90.0_15min.pkl
episodes: 5
horizon: 10
latitude: 0.0
longitude: -90.0
solar_panel_model: constant
start_datetime: '2024-01-30T00:00:00'
threshold_values:
- 0.0
- 0.1
- 0.2
- 0.25
- 0.3
transition_model: moderate
wind_thresholds:
- 0.0
- 2.0
- 4.0
- 6.0
- 8.0
- 10.0
