battery_capacities:
- 200.0
episodes: 5000
failure_penalties:
- 0.0
- 5.0
- 10.0
- 15.0
- 20.0
- 25.0
- 30.0
- 35.0
- 40.0
- 45.0
horizons:
- 3000
locations:
- data_path: Data/EXPECTED_DATA/data_expected_lat30.0_lon-90.0_15min.pkl
  latitude: 30.0
  longitude: -90.0
solar_panel_model: constant
start_datetime: '2024-01-01T00:00:41'
threshold_values:
- 0.1
transition_model: moderate
wind_thresholds:
- 5.0
