battery_capacities:
- 100.0
- 200.0
- 300.0
- 400.0
- 500.0
- 600.0
- 700.0
episodes: 5000
failure_penalties:
- 5.0
horizons:
- 3000
locations:
- data_path: Data/EXPECTED_DATA/data_expected_lat30.0_lon-90.0_15min.pkl
  latitude: 30.0
  longitude: -90.0
- data_path: Data/EXPECTED_DATA/data_expected_lat0.0_lon-90.0_15min.pkl
  latitude: 0.0
  longitude: -90.0
- data_path: Data/EXPECTED_DATA/data_expected_lat-30.0_lon-90.0_15min.pkl
  latitude: -30.0
  longitude: -90.0
solar_panel_model: constant
start_datetime: '2025-06-04T00:00:00'
threshold_values:
- 0.2
transition_model: moderate
wind_thresholds:
- 5.0
