battery_capacities:
- 400.0
data_path: Data/EXPECTED_DATA/data_expected_lat30.0_lon-90.0_15min.pkl
episodes: 10
horizon: 10
latitude: 30.0
longitude: -90.0
solar_panel_model: constant
start_datetime: '2020-04-01T00:00:44'
threshold_values:
- 0.25
transition_model: moderate
wind_thresholds:
- 10.0
