name: Run Tests on Windows with Conda

on:
  push:
    branches:
      - main
      - parametrize-wind-threshold
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]  # Add Windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11.9
          activate-environment: test-env
          use-only-tar-bz2: true  # Important for caching on Windows
          environment-file: environment.yml

      - name: Install mamba
        run: conda install mamba -c conda-forge

      # - name: Cache Conda Environment
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ runner.os == 'Windows' && 'C:/Miniconda3/pkgs' || '~/conda_pkgs_dir' }}
      #     key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-conda-

      - name: Create environment with mamba
        run: mamba env create --file environment.yml --name test-env

      - name: Run Tests
        run: |
          call activate test-env
          python -m unittest discover
